# test provisioning corresponding to the Vagrantfile

- hosts: server-vpn
  user: vagrant
  become: no
  become_method: sudo

  vars:
  - dhprimes_bitlength: 1024 # sufficient to check if it works.
  - int_if: { interface: eth2, ip: 10.10.10.5, netmask: 255.255.255.0 }
  - ext_if: { interface: eth1, ip: 10.10.0.5, netmask: 255.255.255.0 }
  - interfaces:
    - "{{ int_if }}"
    - "{{ ext_if }}"
  - openvpn_server_connect_name: 10.10.0.5

  roles:
  - { role: server-openvpn } 

  tasks:
  - name: set ips
    become: yes
    include: tasks/setupInterfaces.yml

  post_tasks:
  - name: test connectivity - external
    shell: ping -c 1 -I eth1 10.10.0.200
    changed_when: false
    register: ping_ext
    until: ping_ext.stdout.find( "1 packets transmitted, 1 received" ) > -1
    retries: 10
    delay: 3
    tags: tests
    
  - name: test connectivity - internal
    shell: ping -c 1 -I eth2 10.10.10.200
    changed_when: false
    register: ping_int
    until: ping_int.stdout.find( "1 packets transmitted, 1 received" ) > -1
    retries: 10
    delay: 3
    tags: tests
    
  handlers:
  - name: restart networking
    become: yes
    service: name=networking state=restarted

- hosts: server-ext
  user: vagrant
  become: no
  become_method: sudo

  roles:
  - { role: server-openvpn, include_server: false } 

  tasks:
  - debug: msg="external client"

  post_tasks:
  - name: test connectivity
    shell: ping -c 1 -I eth1 10.10.0.5
    changed_when: false
    register: ping_vpn
    until: ping_vpn.stdout.find( "1 packets transmitted, 1 received" ) > -1
    retries: 10
    delay: 3
    tags: tests

  - name: test connectivity through vpn (server)
    shell: ping -c 1 -I tun0 10.10.10.5
    changed_when: false
    register: ping_vpn_tun
    until: ping_vpn_tun.stdout.find( "1 packets transmitted, 1 received" ) > -1
    retries: 10
    delay: 3
    tags: tests

  - name: test connectivity through vpn (server-int)
    shell: ping -c 1 -I tun0 10.10.10.200
    changed_when: false
    register: ping_vpn_int
    until: ping_vpn_int.stdout.find( "1 packets transmitted, 1 received" ) > -1
    retries: 10
    delay: 3
    tags: tests

- hosts: server-int
  user: vagrant
  become: no
  become_method: sudo

#  roles:
#  - { role: server-openvpn } 

  tasks:
  - debug: msg="internal client"

  post_tasks:
  - name: test connectivity
    command: ping -c 1 -I eth1 10.10.10.5
    changed_when: false
    register: ping_vpn
    until: ping_vpn.stdout.find( "1 packets transmitted, 1 received" ) > -1
    retries: 10
    delay: 3
    tags: tests
