# easy rsa certificate handling

# - name: installing easy-rsa
#   apt: 
#     name: [easy-rsa, openvpn] 
#     state: present
  
- name: check easy-rsa presence on ansible host (otherwise install 'easy-rsa')
  shell: 'which make-cadir' 
  changed_when: false

- name: check easy-rsa state
  stat: path={{ easy_rsa_dir }}
  register: easy_rsa_installed

- name: create CA
  shell: make-cadir "{{ easy_rsa_dir }}"
  when: not easy_rsa_installed.stat.exists
  
#- name: create symlink
#  file: src="openssl-1.0.0.cnf" dest="{{ easy_rsa_dir }}/openssl.cnf" state=link

- name: create vars file
  template: src=vars.j2 dest="{{ easy_rsa_dir }}/vars"

- name: create keys dir
  file: state=directory dest={{ easy_rsa_key_dir }} mode=0700

- name: create empty index file
  file:
    path: "{{ easy_rsa_key_dir }}/index.txt"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: create serial minimal serial
  shell: "cd {{ easy_rsa_key_dir }} && echo 01 >> serial"
  args:
    creates: "{{ easy_rsa_key_dir }}/serial"

- name: initialise easy rsa pki
  shell: "cd {{ easy_rsa_dir }} && ./easyrsa init-pki"
  args:
    creates: "{{ easy_rsa_dir }}/pki"

- name: "build easy rsa ca (Note: NO password)"
  shell: "cd {{ easy_rsa_dir }} && ./easyrsa build-ca nopass"
  args:
    creates: "{{ easy_rsa_ca_crt_file }}"

# - name: generate CA key + crt file
#   shell: "cd {{ easy_rsa_dir }} && . ./vars && ./pkitool --initca"
#   args:
#     creates: "{{ easy_rsa_ca_crt_file }}"

- name: generate dh file
  shell: "cd {{ easy_rsa_dir }} && ./easyrsa gen-dh"
  args:
    creates: "{{ easy_rsa_dh_file }}"

- name: generate server key file
  shell: "cd {{ easy_rsa_dir }} && . ./vars && ./pkitool --server {{ openvpn_server_name }}"
  args:
    creates: "{{ easy_rsa_server_key_file }}"

- name: generate HMAC key file
  shell: /usr/sbin/openvpn --genkey --secret {{ easy_rsa_ta_crt_file }}
  args:
    creates: "{{ easy_rsa_ta_crt_file }}"

- name: copy client creation script
  template: src={{ easy_rsa_client_creation_script }}
            dest={{easy_rsa_dir}}/{{ easy_rsa_client_creation_script }}
            mode=0755

- name: create ovpn file
  template: src=client.conf.j2
            dest={{easy_rsa_dir}}/{{ openvpn_client_conf }}
            mode=0755
