# main tasks

- name: include easy-vpn tasks
  become: no
  connection: local
  include: easy-rsa.yml
  when: "{{ use_easy_rsa }}"
  tags: ca

- name: include openvpn tasks
  become: yes
  include: openvpn.yml
  tags: server

