# main tasks

- name: include easy-vpn tasks
  become: no
  connection: local
  include: easy-rsa.yml
  when: "{{ use_easy_rsa }} and {{ include_server }}"
  tags: ca

- name: include openvpn server tasks
  become: yes
  include: openvpn.yml
  when: "{{ include_server }}"
  tags: server

- name: include openvpn client tasks
  become: no
  include: openvpn-client.yml
  when: "{{ include_client }}"
  tags: client

