# setup openvpn

- name: install openvpn packages
  apt: name={{ item }} state=present
  with_items:
  - openvpn

- name: generating new dh primes
  shell: openssl dhparam -out {{ dhprimes_file_server }} {{ dhprimes_bitlength }}
  args:
    creates: "{{ dhprimes_file_server }}"

- name: add open vpn user
  user: name={{ openvpn_user }} shell=/usr/sbin/nologin createhome=no

- name: copy keys to server
  copy: src={{ item.src }} dest={{ item.dest }} 
        owner=root group=root mode=0600
  with_items:
    - { src: "{{ easy_rsa_ta_file }}",  dest: "{{ openvpn_ta_file }}"  }
    - { src: "{{ easy_rsa_ca_file }}",  dest: "{{ openvpn_ca_file }}"  }    
    - { src: "{{ easy_rsa_crt_file }}", dest: "{{ openvpn_crt_file }}" }
    - { src: "{{ easy_rsa_key_file }}", dest: "{{ openvpn_key_file }}" }

