# tasks for the client

- name: create keys bundle for client (locally)
  connection: local
  shell: "./{{ easy_rsa_client_creation_script }} {{ easy_rsa_client_name }}"
  args:
    chdir: "{{ easy_rsa_dir }}"

- name: create folder
  file: path=openvpn state=directory

- name: copy to client
  copy: src="{{ easy_rsa_client_bundle }}"
        dest="openvpn/{{ easy_rsa_client_name }}.tgz"
