# tasks for the client

- name: create keys bundle for client (locally)
  connection: local
  become: no
  shell: "./{{ easy_rsa_client_creation_script }} {{ easy_rsa_client_name }}"
  args:
    chdir: "{{ easy_rsa_dir }}"
    creates: "keys/{{ easy_rsa_client_name }}.key"

- name: install openvpn
  apt: name=openvpn state=present

#- name: create folder
#  file: path=openvpn state=directory

- name: copy to client
  copy: src="{{ easy_rsa_client_bundle }}"
        dest="/etc/openvpn/{{ easy_rsa_client_name }}.tgz"

- name: extract files
  shell: "tar -xvf {{ easy_rsa_client_name }}.tgz"
  args:
    chdir: /etc/openvpn/
  notify: start openvpn client

- name: create symlink to config file
  file: state=link src=/etc/openvpn/{{ openvpn_client_conf }} 
        dest=/etc/openvpn/{{ openvpn_client_conf }}.conf

- name: create log dir
  file: path={{ openvpn_log_dir }} state=directory recurse=true
  
- name: create empty log file
  command: "touch {{ openvpn_log_dir }}/{{ openvpn_log_file }}"
  args:
    creates: "{{ openvpn_log_dir }}/{{ openvpn_log_file }}"
    
- name: create empty status log file
  command: "touch {{ openvpn_log_dir }}/{{ openvpn_status_log_file }}"
  args:
    creates: "{{ openvpn_log_dir }}/{{ openvpn_status_log_file }}"

- name: enable openvpn service - client
  service: name="{{ openvpn_service_client }}" enabled=yes

