# setup openvpn

- name: install openvpn packages
  apt: name={{ item }} state=present
  with_items:
  - openvpn
  tags: openvpn

- name: generating new dh primes
  shell: openssl dhparam -out {{ dhprimes_file_server }} {{ dhprimes_bitlength }}
  args:
    creates: "{{ dhprimes_file_server }}"

- name: add open vpn user
  user: name={{ openvpn_user }} shell=/usr/sbin/nologin createhome=no
