# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "deb8-base"
  config.vm.hostname = "server-openvpn-test"

  config.vm.provider :libvirt do |libvirt|
    libvirt.host = ""
    libvirt.nested = true
    libvirt.memory = 512
  end

    config.vm.network :private_network, 
      :ip => "10.10.0.5",
      :libvirt__forward_mode => "nat",
      :libvirt__network_name => "LAN_upstream",
      :auto_config => false,
      :libvirt__dhcp_enabled => false

    config.vm.network :private_network, 
      :ip => "10.10.10.5",
      :libvirt__forward_mode => "none",
      :libvirt__network_name => "LAN_A",
      :auto_config => false,
      :libvirt__dhcp_enabled => false
      
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
  end
  
end
