- name: start openvpn server
  become: yes
  service: name={{ openvpn_service_server }} state=started
  
- name: start openvpn client
  become: yes
  service: name={{ openvpn_service_client }} state=started
  
