- name: restart openvpn server
  become: yes
  service: 
    name: "{{ openvpn_service_server }}" 
    state: restarted
  
- name: start openvpn client
  become: yes
  service: 
    name: "{{ openvpn_service_client }}"
    state: started
  
- name: run rc.local
  become: yes
  shell: "/etc/rc.local"
